server {
    listen 80;
    server_name web1.vutuyet.id.vn;

    root /usr/share/nginx/website1;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name web2.vutuyet.id.vn;

    root /usr/share/nginx/website2;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
